### PR TITLE
Hebase

### PR DESCRIPTION
**Pull request by aehud**
hebase + 2 demos + tutorials

### CODE REVIEW

**Comment by dubek** [comment]
Note that this adds a new `DEPENDENCIES/hedge` folder (which is built in the Dockerfile) and three new examples: hedge_BGV_country_db_lookup, hedge_credit_card_fraud, and hedge_tutorials. This doesn't modify existing library and examples.

After this is successfully merged, we can issue another PR (or just modify the main repo) to remove existing examples (`BGV_country_db_lookup` and `credit_card_fraud`) and the older library (`DEPENDENCIES/simple_ml_helib`), as well as removing it from the Dockerfile.

**Comment by aehud** [comment]
Another two points to discuss:
* Current build scripts compile the unit tests, but do not run them.||
* We have doxygen style comments. I can add the Doxyfile and we can automate if it makes sense.

**Comment by dowem** [comment]
@aehud 

1: If you can show how to run the commands to @boland25 he can add them to our regression pipeline for build and promotion to docker hub. 

2: Definitely include the doxygen stuff to build the docs and we can ship it with the other nicely formatted docs with our nice doxygen theme.

**Comment by dowem** [comment]
> Note that this adds a new `DEPENDENCIES/hedge` folder (which is built in the Dockerfile) and three new examples: hedge_BGV_country_db_lookup, hedge_credit_card_fraud, and hedge_tutorials. This doesn't modify existing library and examples.
> 
> After this is successfully merged, we can issue another PR (or just modify the main repo) to remove existing examples (`BGV_country_db_lookup` and `credit_card_fraud`) and the older library (`DEPENDENCIES/simple_ml_helib`), as well as removing it from the Dockerfile.

Hi @dubek it looks like your commits were not signed with the keys so I think this wont merge as is. In the commits above they ar emissing the "verified" label. Perhaps @aehud can get you hooked up with the setuo for signing the commits before the next PR submission?

**Comment by dubek** [comment]
@EliDowWeather : @aehud  solved it by squashing and pushing one big signed verified genuine authentic official celebratory commit.

**Comment by aehud** [comment]
Some updates:
* Added a doxyfile in the root of hedge
* Added a run_all_tests.sh script in hedge/make, from which it should be executed. A few unit tests create a directory "./output" and write stuff to it, so they should have permission for it.

**Comment by aehud** [comment]
Outdated. Sending another PR.

**Pull request closed without merging**
